# Copyright 2015-2016 CNRS-UM LIRMM, CNRS-AIST JRL
#
# This file is part of eigen-qld.
#
# eigen-qld is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# eigen-qld is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with eigen-qld.  If not, see <http://www.gnu.org/licenses/>.
sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
  - clang
env:
  global:
  - APT_DEPENDENCIES="doxygen doxygen-latex libboost-all-dev gfortran"
  - GIT_DEPENDENCIES=""
notifications:
  email:
  - pierre.gergondet@gmail.com
script: ./.jrl-ci/run build
after_success: ./.jrl-ci/run after_success
after_failure: ./.jrl-ci/run after_failure
before_install:
  - ./.jrl-ci/dependencies/eigen-3.2
  - ./.jrl-ci/run  before_install
matrix:
  allow_failures:
    - compiler: clang
