#
# Copyright 2012-2019 CNRS-UM LIRMM, CNRS-AIST JRL
#

dist: xenial
addons:
  apt:
    packages:
    - doxygen
    - doxygen-latex
    - libboost-all-dev
    - libeigen3-dev
    - python-pip
    - python3-pip
    - cython
    - python-nose
    - python-numpy
    - python-coverage
    - cython3
    - python3-nose
    - python3-numpy
    - python3-coverage
    - python3-setuptools
    - gfortran
    - libgfortran-5-dev
branches:
  except:
    - debian
language: cpp
compiler:
- gcc
- clang
env:
  global:
  - APT_DEPENDENCIES=""
  - GIT_DEPENDENCIES="jrl-umi3218/Eigen3ToPython"
  - CMAKE_ADDITIONAL_OPTIONS="-DPYTHON_BINDING_BUILD_PYTHON2_AND_PYTHON3:BOOL=ON -DPYTHON_BINDING_USER_INSTALL:BOOL=ON"
notifications:
  slack:
    secure: GfSvOYWJb5LM3NZbuK9PtQN6Ge7RUvfK7H1PQy55hPCVnac4ZMDg49phqkuoN1FCKDxfH9COsxFJ6ZUgOVU/ZLq/3MX3UBiE56N+T+C1St/V1caeELUPYSr0P7Fnbjk1DEO3EBthv3iP6lK3WLyXMZkOrbpVgM0xakR/vUsWSP/Fhdm5R+sNYmS2BTMzUibX9o7M4ZWb4UTPOGBvVQq1pSLJ/cVLBEo/IE+S1VHKvcc5CGdptkXdexezi7i9qtB5jvP40zpBYEzxdne5a/KJLtcWGPHcvnRlEZwYzO8oNw1IqdBC/2tIUIfl8zj0qUnJIiWyWUotIMF3dQHHBY5Ehvzrcq2jVctdbGkN1Jo3T+pM6FkT7JXuGJJ/NuMMpQDgMSoXDVpMbPufutqE4ZFwr1XU6gkNvGwIcXl94pVEGx0csNxc3L9egSGjsmYdSWKToltU78ydCEjPpILe8hUtBn0R11WmbBdPlKR1WPCdasLuvKMHpwDU4/U4qpuaDcgIo04lPasfeUMtgkfSkV/oWeCntV88T/aX55uaOeSARwKPuqRahDdRzUrxEVsNDQXguiBMSNrbTCYlv1BOuIgZikucZuzdcq84/0LSJgvf9bon29bTu/1M0N4rSpJJOKgE5kab9E7fQ3EAULH5odTtPxqwZmqzFnI3bW16qP8RxXs=
before_install: ./.jrl-ci/run  before_install
script: ./.jrl-ci/run build
after_success: ./.jrl-ci/run after_success
after_failure: ./.jrl-ci/run after_failure
